// Norberts mobile Fußpflege — English shop language file (en/).
// Loaded BEFORE js/produkte.js on the English shop pages; provides the
// path base, interface texts, category titles and all product translations.
// NOTE: The order message to Norbert always uses the German names/values.
window.NF_BASIS = '../';

window.NF_TEXTE = {
  artikel:         'items',
  titelZusatz:     ' – Norberts mobile Fußpflege Stuttgart',
  badgeNeu:        'New',
  badgeBestseller: 'Bestseller',
  aufLager:        '● In stock',
  wenig:           '● Only a few left',
  vonSternen:      'out of 5 stars',
  mengeMinus:      'Decrease quantity',
  mengePlus:       'Increase quantity',
  inDenKorb:       'Add to cart',
  imKorb:          '✓ Added to cart',
  jetztKaufen:     'Buy now',
  entfernen:       'remove'
};

window.NF_KATEGORIEN = {
  w: 'Tools, Instruments & Hygiene',
  c: 'Creams & Balms',
  e: 'Electric Devices',
  b: 'Foot Baths & Additives',
  n: 'Nail Care',
  h: 'Callus & Exfoliation',
  k: 'Comfort & Relief',
  g: 'Gifts & Vouchers'
};

window.NF_UEBERSETZUNG = {
  /* --- Tools & instruments --- */
  w1:  { name: 'Stainless Steel Callus Nippers',      info: 'Rust-free stainless steel, precision-ground – for gentle callus removal.',      inhalt: '1 piece · 14 cm' },
  w2:  { name: 'Professional Nail Nippers',           info: 'Powerful leverage, a clean cut even on strong nails.',                          inhalt: '1 piece · 12 cm' },
  w4:  { name: 'Instrument Case, 3 Pieces',           info: 'Nippers, file and scraper in a leather case – ideal for on the go.',            inhalt: 'Set of 3' },
  w5:  { name: 'Foot Care Scraper with Blade',        info: 'Secure grip, replaceable blades – for experienced hands only.',                 inhalt: '1 piece + 10 blades' },
  w6:  { name: 'Curved Toenail Scissors',             info: 'The curved blade follows the nail shape – gentle and precise.',                 inhalt: '1 piece · 10 cm' },
  w7:  { name: 'Double-Ended Cuticle Pusher',         info: 'Pushes back and loosens the cuticle – two working ends.',                       inhalt: '1 piece' },
  w9:  { name: 'Instrument Cleaning Brush',           info: 'Fine brass bristles – keeps files and burs clean.',                             inhalt: '1 piece' },
  w10: { name: 'Foot Care Starter Set',               info: 'The 6 most important tools in a case – the ideal way to start.',                inhalt: 'Set of 6' },

  /* --- Creams & balms --- */
  c1:  { name: 'Foot Cream Urea 10 %',                info: 'Intensive moisture for dry, stressed feet.',                                    inhalt: '100 ml' },
  c2:  { name: 'Marigold Foot Balm',                  info: 'Soothes and nourishes – with calendula and beeswax.',                           inhalt: '75 ml' },
  c3:  { name: 'Intensive Cracked-Heel Ointment',     info: 'Rich care for very dry heels.',                                                 inhalt: '75 ml' },
  c4:  { name: 'Fresh Foot Deodorant Spray',          info: 'Long-lasting freshness, dermatologically tested.',                              inhalt: '100 ml' },
  c5:  { name: 'Shea Foot Butter',                    info: 'Gently melting overnight care – with shea and almond.',                         inhalt: '150 ml' },
  c6:  { name: 'Cooling Mint Foot Gel',               info: 'Refreshes tired legs and feet – absorbs quickly.',                              inhalt: '100 ml' },
  c7:  { name: 'Rosemary Massage Oil',                info: 'Warming oil for foot massages at home.',                                        inhalt: '100 ml' },
  c8:  { name: 'Anti-Callus Cream',                   info: 'Visibly softens hardened skin overnight.',                                      inhalt: '75 ml' },
  c9:  { name: 'Express Care Foam',                   info: 'Absorbs in seconds – care without the wait.',                                   inhalt: '125 ml' },
  c10: { name: 'Winter Care Duo',                     info: 'Foot cream + cracked-heel ointment in a value set.',                            inhalt: 'Set, 2 × 75 ml' },
  c11: { name: 'Foot Cream Urea 25 % Intensive',      info: 'The strong formula for very dry, cracked skin.',                                inhalt: '75 ml' },
  c12: { name: 'Evening Primrose Balm',               info: 'Calms irritated, sensitive skin overnight.',                                    inhalt: '50 ml' },
  c13: { name: 'Zinc Care Cream',                     info: 'Supports stressed skin – absorbs quickly.',                                     inhalt: '50 ml' },
  c14: { name: 'Warming Ginger Foot Balm',            info: 'Pleasant warmth for cold feet – ideal in winter.',                              inhalt: '75 ml' },
  c15: { name: 'Fragrance-Free Sensitive Cream',      info: 'No fragrances or colourants – for sensitive skin.',                             inhalt: '100 ml' },
  c16: { name: 'Care Trio Trial Sizes',               info: 'Cream, balm and foam to try them out.',                                         inhalt: 'Set, 3 × 30 ml' },

  /* --- Electric devices --- */
  e1:  { name: 'Electric Callus Remover',             info: 'Two speeds, rechargeable – gently smooth heels.',                               inhalt: '1 device + 2 rollers' },
  e2:  { name: 'Nail Drill Set, 10 Pieces',           info: 'Quiet device with 10 attachments for nail and callus care.',                    inhalt: '1 set' },
  e3:  { name: 'Bubble Foot Spa with Heat',           info: 'Bubbles, vibration and a heat function – wellness at home.',                    inhalt: '1 device' },
  e4:  { name: 'Replacement Grinding Rollers (3 pack)', info: 'Fits the callus remover – medium grit.',                                      inhalt: '3 pieces' },
  e5:  { name: 'UV Dryer for Care Polish',            info: 'Dries care polishes in 60 seconds.',                                            inhalt: '1 device' },
  e6:  { name: 'Electric Nail File Pen',              info: 'As handy as a pen – for shape and shine.',                                      inhalt: '1 device + 4 attachments' },
  e7:  { name: 'Shiatsu Foot Massager',               info: 'Rotating massage heads with heat – deeply relaxing.',                           inhalt: '1 device' },
  e8:  { name: 'Replacement Drill Bits (5 pack)',     info: 'Fine diamond bits for the drill set.',                                          inhalt: '5 pieces' },
  e9:  { name: 'Paraffin Bath for Feet',              info: 'Warm paraffin for velvety-soft skin – incl. 450 g of wax.',                     inhalt: '1 device + wax' },
  e10: { name: 'Travel Case for Devices',             info: 'Padded hard case for file, drill and accessories.',                             inhalt: '1 piece' },
  e11: { name: 'Cordless Nail Polisher',              info: 'Polish and seal – cordless, with 3 attachments.',                               inhalt: '1 device + 3 attachments' },
  e12: { name: 'UV Disinfection Box',                 info: 'Disinfects instruments in 8 minutes – without chemicals.',                      inhalt: '1 device' },
  e13: { name: 'Replacement Grinding Rollers, Fine (3 pack)', info: 'Fine grit for the finish after the callus remover.',                    inhalt: '3 pieces' },
  e14: { name: 'Mini Travel-Size Nail Drill',         info: 'Small as a ballpoint pen – full power on the go.',                              inhalt: '1 device + 2 attachments' },
  e15: { name: 'Electric Foot Warmer',                info: 'Cosy warming boot with 3 levels and automatic shut-off.',                       inhalt: '1 device' },
  e16: { name: 'Air Compression Massager',            info: 'Gentle alternating pressure for feet and calves – 2 cuffs.',                    inhalt: '1 device' },

  /* --- Foot baths & additives --- */
  b1:  { name: 'Dead Sea Foot Bath Salt',             info: 'Mineral-rich salt – relaxes and nourishes.',                                    inhalt: '500 g' },
  b2:  { name: 'Rosemary Foot Bath Additive',         info: 'Invigorating bath additive for tired feet.',                                    inhalt: '250 ml' },
  b3:  { name: 'Lavender Fizzing Tabs (8 pack)',      info: 'One tab per foot bath – calming lavender scent.',                               inhalt: '8 tabs' },
  b4:  { name: 'Foldable Foot Basin',                 info: 'Folds flat to save space, with a non-slip base.',                               inhalt: '1 piece' },
  b5:  { name: 'Milk Bath for Feet',                  info: 'Creamy bath additive with milk proteins.',                                      inhalt: '400 ml' },
  b6:  { name: 'Alkaline Foot Bath Powder',           info: 'Alkaline pH for a soothing, long bath.',                                        inhalt: '300 g' },
  b7:  { name: 'Foot Bath Thermometer',               info: 'Shows the ideal water temperature at a glance.',                                inhalt: '1 piece' },
  b8:  { name: 'Massage Brush for the Bath',          info: 'Soft nubs massage the sole in the foot bath.',                                  inhalt: '1 piece' },
  b9:  { name: 'Eucalyptus Bath Oil',                 info: 'Refreshing oil – two capfuls per foot bath are enough.',                        inhalt: '200 ml' },
  b10: { name: 'Complete Foot Bath Set',              info: 'Basin, salt, brush and towel in one set.',                                      inhalt: 'Set of 4' },
  b11: { name: 'Lavender Foot Bath Salt',             info: 'Calming lavender for an evening bath.',                                         inhalt: '500 g' },
  b12: { name: 'Mint Fizzing Tabs (8 pack)',          info: 'Refreshing mint – one tab per foot bath.',                                      inhalt: '8 tabs' },
  b13: { name: 'Chamomile Foot Bath Additive',        info: 'The mild classic for sensitive skin.',                                          inhalt: '250 ml' },
  b14: { name: 'Tea Tree Oil Bath Additive',          info: 'The fresh additive for stressed feet.',                                         inhalt: '100 ml' },
  b15: { name: 'Foot Basin with Massage Nubs',        info: 'The nubbed base massages the sole while you bathe.',                            inhalt: '1 piece' },
  b16: { name: 'Foot Bath Duo Salt & Oil',            info: 'Dead Sea salt and eucalyptus oil in a value set.',                              inhalt: 'Set of 2' },

  /* --- Nail care --- */
  n1:  { name: 'Nail Oil with Pipette',               info: 'Jojoba and vitamin E – strengthens nail and cuticle.',                          inhalt: '10 ml' },
  n2:  { name: 'Nail Clippers XL',                    info: 'Extra large grip – even for strong toenails.',                                  inhalt: '1 piece' },
  n3:  { name: 'Glass File in a Case',                info: 'Seals the nail edge – stays sharp for a lifetime.',                             inhalt: '1 piece' },
  n4:  { name: '2-in-1 Nail Care Pen',                info: 'Oil pen and pusher in one – for on the go.',                                    inhalt: '1 piece' },
  n5:  { name: 'Clear Care Polish',                   info: 'Strengthening base coat with a silky shine.',                                   inhalt: '10 ml' },
  n6:  { name: '4-Sided Buffer Block',                info: 'File, smooth, polish, seal – all in one block.',                                inhalt: '1 piece' },
  n7:  { name: 'Cuticle Remover Gel',                 info: 'Loosens excess cuticle in 60 seconds.',                                         inhalt: '30 ml' },
  n8:  { name: 'Nail Repair Serum',                   info: 'Visibly rebuilds brittle nails in 4 weeks.',                                    inhalt: '15 ml' },
  n9:  { name: 'File Set, Mixed Grits (6 pack)',      info: 'Six files from coarse to super fine.',                                          inhalt: '6 pieces' },
  n10: { name: 'Complete Nail Care Set',              info: 'Oil, clippers, glass file and pen in a gift box.',                              inhalt: 'Set of 4' },
  n11: { name: 'Rose-Scented Cuticle Oil',            info: 'Nourishes the cuticle – with a delicate rose scent.',                           inhalt: '10 ml' },
  n12: { name: 'Nail Whitening Pen',                  info: 'Visibly brightens the free nail edge.',                                         inhalt: '1 piece' },
  n13: { name: 'Straight Nail Scissors',              info: 'A straight cut helps prevent ingrown corners.',                                 inhalt: '1 piece · 10 cm' },
  n14: { name: 'Emery Boards (10 pack)',              info: 'Refill pack for daily nail care.',                                              inhalt: '10 pieces' },
  n15: { name: 'Nail Hardener Polish',                info: 'Noticeably hardens soft nails in 2 weeks.',                                     inhalt: '10 ml' },
  n16: { name: 'Manicure Case, 7 Pieces',             info: 'All the nail tools in a zip-up case.',                                          inhalt: 'Set of 7' },

  /* --- Callus & exfoliation --- */
  h1:  { name: 'Natural Pumice Stone',                info: 'Genuine volcanic pumice – the classic for the shower.',                         inhalt: '1 piece' },
  h2:  { name: 'Double-Sided Callus Rasp',            info: 'Coarse and fine side – for heel and ball of the foot.',                         inhalt: '1 piece' },
  h3:  { name: 'Sea Salt Foot Scrub',                 info: 'Fine salt scrub with almond oil – velvety skin.',                               inhalt: '150 ml' },
  h4:  { name: 'Callus Reducing Cream',               info: 'Daily care that helps prevent new calluses.',                                   inhalt: '75 ml' },
  h5:  { name: 'Exfoliating Socks (1 pair)',          info: 'Apply, peel off, be amazed – renewed skin in 7 days.',                          inhalt: '1 pair' },
  h6:  { name: 'Vanilla Sugar Scrub',                 info: 'Gentle scrub for sensitive skin.',                                              inhalt: '200 ml' },
  h7:  { name: 'Ceramic Callus Stone',                info: 'Finer than pumice – ideal for the finish.',                                     inhalt: '1 piece' },
  h8:  { name: 'Sisal Exfoliating Glove',             info: 'Natural-fibre glove for feet and legs.',                                        inhalt: '1 piece' },
  h9:  { name: 'Urea Foot Mask',                      info: 'Intensive mask with 15 % urea – leave on overnight.',                           inhalt: '100 ml' },
  h10: { name: 'Smooth Feet Set',                     info: 'Rasp, scrub and reducing cream in one set.',                                    inhalt: 'Set of 3' },
  h11: { name: 'Replacement Blades (10 pack)',        info: 'Fits the foot care scraper – individually sealed.',                             inhalt: '10 pieces' },
  h12: { name: 'Foot Brush with Pumice Back',         info: 'Bristles and pumice stone in one handle.',                                      inhalt: '1 piece' },
  h13: { name: 'Invigorating Coffee Scrub',           info: 'Ground coffee and coconut oil – wakes up tired feet.',                          inhalt: '200 ml' },
  h14: { name: 'Callus Balm Urea 10 %',               info: 'Daily care after using the rasp or file.',                                      inhalt: '100 ml' },
  h15: { name: 'Exfoliating Socks, Double Pack',      info: 'Two applications – for a treat every 3 months.',                                inhalt: '2 pairs' },
  h16: { name: 'Smooth Heels 7-Day Programme',        info: 'Mask, balm and instructions for one week.',                                     inhalt: 'Set of 2' },

  /* --- Comfort & relief --- */
  k1:  { name: 'Gel Toe Spreaders (2 pack)',          info: 'Soft gel relieves cramped toes.',                                               inhalt: '2 pieces' },
  k2:  { name: 'Pressure Protection Rings (6 pack)',  info: 'Self-adhesive pads against rubbing in the shoe.',                               inhalt: '6 pieces' },
  k3:  { name: 'Gel Heel Cushions (pair)',            info: 'Cushions every step – can be cut to fit any shoe.',                             inhalt: '1 pair' },
  k4:  { name: 'Cosy Wellness Socks',                 info: 'Fluffy socks with a non-slip sole – a dream after your care session.',          inhalt: '1 pair, sizes 36–42' },
  k5:  { name: 'Gel Toe Protection Caps (4 pack)',    info: 'Protect sensitive toes in any shoe.',                                           inhalt: '4 pieces' },
  k6:  { name: 'Self-Adhesive Ball-of-Foot Pads',     info: 'Relieves the forefoot when standing for long periods.',                         inhalt: '4 pieces' },
  k7:  { name: 'Wooden Massage Roller',               info: 'Simply roll tension away – made of beech wood.',                                inhalt: '1 piece' },
  k8:  { name: 'Spiky Massage Ball Duo',              info: 'Two nubbed balls for an active massage in between.',                            inhalt: '2 pieces' },
  k9:  { name: 'Gel Comfort Insoles',                 info: 'Cushioning gel insoles, can be cut to size, 36–46.',                            inhalt: '1 pair' },
  k10: { name: 'Foot Exercise Set',                   info: 'Ball, band and exercise guide for strong feet.',                                inhalt: 'Set of 3' },
  k11: { name: 'Light Support Socks (pair)',          info: 'Gentle compression for long days on your feet.',                                inhalt: '1 pair, sizes 36–46' },
  k12: { name: 'Heel Cushions (pair)',                info: 'Soft padding relieves the heel with every step.',                               inhalt: '1 pair' },
  k13: { name: 'Toe Yoga Spreaders (pair)',           info: 'Stretches the toes after a long day in shoes.',                                 inhalt: '1 pair' },
  k14: { name: 'Acupressure Mat for Feet',            info: 'A field of nubs for a standing foot massage.',                                  inhalt: '1 piece · 35 × 35 cm' },
  k15: { name: 'Oversized Foot Hot-Water Bottle',     info: 'Extra wide – warms both feet at the same time.',                                inhalt: '1 piece · 2 l' },
  k16: { name: 'Non-Slip Socks (2 pairs)',            info: 'Secure grip on smooth floors – washable at 60 °C.',                             inhalt: '2 pairs, sizes 36–46' },

  /* --- Hygiene & disinfection --- */
  d1:  { name: 'Hand Sanitiser Gel',                  info: 'Gentle on the skin, with aloe – for on the go.',                                inhalt: '100 ml' },
  d2:  { name: 'Surface Disinfectant Spray',          info: 'Fast-acting – for devices and work surfaces.',                                  inhalt: '250 ml' },
  d3:  { name: 'Nitrile Disposable Gloves (100)',     info: 'Powder-free, tear-resistant – sizes S to XL.',                                  inhalt: '100 pieces' },
  d4:  { name: 'Antibacterial Foot Spray',            info: 'Refreshes and protects – ideal after sport.',                                   inhalt: '150 ml' },
  d5:  { name: 'Instrument Disinfection Bath',        info: 'Tray with strainer insert for instrument care.',                                inhalt: '1 piece · 1 l' },
  d6:  { name: 'Disinfectant Concentrate',            info: 'Makes up to 25 l of ready-to-use solution.',                                    inhalt: '500 ml' },
  d7:  { name: 'Disposable Underlays (50 pack)',      info: 'Highly absorbent and hygienic – 40 × 60 cm.',                                   inhalt: '50 pieces' },
  d9:  { name: 'Hygiene Travel Set',                  info: 'Gel, spray and wipes in a toiletry bag.',                                       inhalt: 'Set of 3' },

  /* --- Gifts & vouchers --- */
  g1:  { name: 'Professional Foot Care Voucher',      info: 'The classic gift – the complete care session as a home visit.',                 inhalt: '1 voucher' },
  g2:  { name: 'Foot Massage Voucher',                info: 'Give the gift of relaxation – a soothing massage at home.',                     inhalt: '1 voucher' },
  g3:  { name: 'Reflexology Foot Massage Voucher',    info: 'The most extensive session as a gift.',                                         inhalt: '1 voucher' },
  g4:  { name: '€25 Gift Voucher',                    info: 'Freely redeemable for services and products.',                                  inhalt: '1 voucher' },
  g5:  { name: '"Happy Feet" Pampering Set',          info: 'Foot bath salt, cream and wellness socks in a gift box.',                       inhalt: 'Set of 3' },
  g6:  { name: '"Foot Rescue" Gift Box',              info: 'Scrub, balm and nail oil – beautifully packaged.',                              inhalt: 'Set of 3' },
  g7:  { name: '"Foot Works" Men\'s Set',             info: 'Rasp, cream and freshness spray for him.',                                      inhalt: 'Set of 3' },
  g8:  { name: 'Greeting Card with Envelope',         info: 'The perfect match for a voucher – "For You".',                                  inhalt: '1 piece' },
  g9:  { name: 'Premium Gift Wrapping',               info: 'Box, tissue paper and ribbon – ready-wrapped.',                                 inhalt: '1 piece' },
  g10: { name: 'Annual Package "4 × Care"',           info: 'Four professional foot care visits in advance – one visit free.',               inhalt: '4 vouchers' },
  g11: { name: '€50 Gift Voucher',                    info: 'Freely redeemable for services and products.',                                  inhalt: '1 voucher' },
  g12: { name: '€100 Gift Voucher',                   info: 'The big gift – freely redeemable.',                                             inhalt: '1 voucher' },
  g13: { name: '"For Two" Duo Voucher',               info: 'Two professional foot care visits – e.g. for couples.',                         inhalt: '2 vouchers' },
  g14: { name: '"Winter Feet" Gift Set',              info: 'Warming balm, cosy socks and bath salt.',                                       inhalt: 'Set of 3' },
  g15: { name: 'A Little Treat',                      info: 'Handy foot cream with a greeting card – the small gesture.',                    inhalt: 'Set of 2' },
  g16: { name: 'Voucher by Email',                    info: 'Sent straight away – ideal for last-minute gifts.',                             inhalt: '1 voucher (PDF)' }
};
