// Norberts mobile Fußpflege — Türkische Shop-Übersetzung (tr/).
// Wird VOR js/produkte.js geladen und stellt Pfad-Basis, Oberflächen-Texte,
// Bereichs-Titel und alle Produkt-Übersetzungen bereit.
// WICHTIG: Der Bestelltext an Norbert nutzt weiterhin die deutschen Namen.

window.NF_BASIS = '../';

window.NF_TEXTE = {
  artikel: 'ürün',
  titelZusatz: ' – Norberts mobile Fußpflege Stuttgart',
  badgeNeu: 'Yeni',
  badgeBestseller: 'Çok satan',
  aufLager: '● Stokta',
  wenig: '● Son birkaç adet',
  vonSternen: '/ 5 yıldız',
  mengeMinus: 'Adedi azalt',
  mengePlus: 'Adedi artır',
  inDenKorb: 'Sepete ekle',
  imKorb: '✓ Sepette',
  jetztKaufen: 'Hemen satın al',
  entfernen: 'sepetten çıkar'
};

window.NF_KATEGORIEN = {
  w: 'Aletler, Enstrümanlar ve Hijyen',
  c: 'Kremler ve Balsamlar',
  e: 'Elektrikli Cihazlar',
  b: 'Ayak Banyoları ve Katkılar',
  n: 'Tırnak Bakımı',
  h: 'Nasır ve Peeling',
  k: 'Konfor ve Rahatlama',
  g: 'Hediyeler ve Hediye Çekleri'
};

window.NF_UEBERSETZUNG = {
  /* --- Werkzeuge & Instrumente --- */
  w1:  { name: 'Paslanmaz Çelik Nasır Pensi',           info: 'Paslanmaz çelik, hassas bileme – nasırın nazikçe alınması için.',            inhalt: '1 adet · 14 cm' },
  w2:  { name: 'Profesyonel Tırnak Pensi',              info: 'Güçlü kol mekanizması, kalın tırnaklarda bile temiz kesim.',                 inhalt: '1 adet · 12 cm' },
  w4:  { name: '3 Parçalı Alet Çantası',                info: 'Pens, törpü ve raspa deri kılıf içinde – yolculuk için ideal.',              inhalt: '3 parçalı set' },
  w5:  { name: 'Bıçaklı Ayak Bakım Raspası',            info: 'Güvenli tutuş, değiştirilebilir bıçaklar – yalnızca deneyimli eller için.',  inhalt: '1 adet + 10 bıçak' },
  w6:  { name: 'Kavisli Ayak Tırnak Makası',            info: 'Kavisli ağız tırnağın şeklini izler – nazik ve hassas.',                     inhalt: '1 adet · 10 cm' },
  w7:  { name: 'Çift Uçlu Tırnak Eti İticisi',          info: 'Tırnak etini iter ve gevşetir – iki çalışma ucu.',                           inhalt: '1 adet' },
  w9:  { name: 'Alet Temizleme Fırçası',                info: 'İnce pirinç kıllar – törpü ve frezeleri temiz tutar.',                       inhalt: '1 adet' },
  w10: { name: 'Ayak Bakımı Başlangıç Seti',            info: 'En önemli 6 alet kılıf içinde – başlamak için ideal.',                       inhalt: '6 parçalı set' },

  /* --- Cremes & Balsame --- */
  c1:  { name: 'Ayak Kremi Üre %10',                    info: 'Kuru ve yıpranmış ayaklar için yoğun nem.',                                  inhalt: '100 ml' },
  c2:  { name: 'Aynısefa Ayak Balsamı',                 info: 'Yatıştırır ve besler – kalendula ve balmumu içerir.',                        inhalt: '75 ml' },
  c3:  { name: 'Yoğun Topuk Çatlağı Merhemi',           info: 'Çok kuru topuklar için zengin bakım.',                                       inhalt: '75 ml' },
  c4:  { name: 'Ferahlatıcı Ayak Deodorantı',           info: 'Uzun süre kalıcı ferahlık, dermatolojik olarak test edilmiştir.',            inhalt: '100 ml' },
  c5:  { name: 'Shea Yağlı Ayak Kremi',                 info: 'Gece için yumuşacık eriyen bakım – shea ve badem içerir.',                   inhalt: '150 ml' },
  c6:  { name: 'Naneli Serinletici Ayak Jeli',          info: 'Yorgun bacak ve ayakları ferahlatır – hızla emilir.',                        inhalt: '100 ml' },
  c7:  { name: 'Biberiyeli Masaj Yağı',                 info: 'Evde ayak masajı için ısıtıcı etkili yağ.',                                  inhalt: '100 ml' },
  c8:  { name: 'Nasır Karşıtı Krem',                    info: 'Sertleşmiş bölgeleri gece boyunca gözle görülür şekilde yumuşatır.',         inhalt: '75 ml' },
  c9:  { name: 'Ekspres Bakım Köpüğü',                  info: 'Saniyeler içinde emilir – beklemeden bakım.',                                inhalt: '125 ml' },
  c10: { name: 'Kış Bakım İkilisi',                     info: 'Ayak kremi + topuk çatlağı merhemi avantajlı sette.',                        inhalt: '2 × 75 ml set' },
  c11: { name: 'Yoğun Ayak Kremi Üre %25',              info: 'Çok kuru, çatlamış cilt için güçlü formül.',                                 inhalt: '75 ml' },
  c12: { name: 'Çuha Çiçeği Yağlı Balsam',              info: 'Tahriş olmuş, hassas cildi gece boyunca yatıştırır.',                        inhalt: '50 ml' },
  c13: { name: 'Çinkolu Bakım Kremi',                   info: 'Yıpranmış cildi destekler – hızla emilir.',                                  inhalt: '50 ml' },
  c14: { name: 'Zencefilli Isıtıcı Ayak Balsamı',       info: 'Soğuk ayaklara hoş bir sıcaklık – kışın ideal.',                             inhalt: '75 ml' },
  c15: { name: 'Parfümsüz Hassas Cilt Kremi',           info: 'Koku ve boyar madde içermez – hassas ciltler için.',                         inhalt: '100 ml' },
  c16: { name: 'Deneme Boyu Bakım Üçlüsü',              info: 'Tanımak için krem, balsam ve köpük.',                                        inhalt: '3 × 30 ml set' },

  /* --- Elektrische Geräte --- */
  e1:  { name: 'Elektrikli Nasır Törpüsü',              info: 'İki hız kademesi, şarj edilebilir – pürüzsüz topuklar.',                     inhalt: '1 cihaz + 2 rulo' },
  e2:  { name: '10 Parçalı Tırnak Freze Seti',          info: 'Tırnak ve nasır bakımı için 10 başlıklı sessiz cihaz.',                      inhalt: '1 set' },
  e3:  { name: 'Isıtmalı Kabarcıklı Ayak Banyosu',      info: 'Kabarcık, titreşim ve ısıtma işlevi – evde spa keyfi.',                      inhalt: '1 cihaz' },
  e4:  { name: 'Yedek Zımpara Ruloları (3\'lü)',        info: 'Nasır törpüsüyle uyumlu – orta kum kalınlığı.',                              inhalt: '3 adet' },
  e5:  { name: 'Bakım Ojesi için UV Kurutucu',          info: 'Bakım ojelerini 60 saniyede kurutur.',                                       inhalt: '1 cihaz' },
  e6:  { name: 'Kalem Tipi Elektrikli Tırnak Törpüsü',  info: 'Kalem gibi kullanışlı – şekil ve parlaklık için.',                           inhalt: '1 cihaz + 4 başlık' },
  e7:  { name: 'Shiatsu Ayak Masaj Cihazı',             info: 'Isıtmalı dönen masaj başlıkları – derinlemesine rahatlatır.',                inhalt: '1 cihaz' },
  e8:  { name: 'Yedek Freze Başlıkları (5\'li)',        info: 'Freze seti için ince elmas başlıklar.',                                      inhalt: '5 adet' },
  e9:  { name: 'Ayaklar için Parafin Banyosu',          info: 'Kadife gibi bir cilt için sıcak parafin – 450 g parafin dahil.',             inhalt: '1 cihaz + parafin' },
  e10: { name: 'Cihazlar için Seyahat Çantası',         info: 'Törpü, freze ve aksesuarlar için yastıklı sert çanta.',                      inhalt: '1 adet' },
  e11: { name: 'Şarjlı Tırnak Parlatıcı',               info: 'Parlatır ve korur – kablosuz, 3 başlıklı.',                                  inhalt: '1 cihaz + 3 başlık' },
  e12: { name: 'UV Dezenfeksiyon Kutusu',               info: 'Aletleri 8 dakikada dezenfekte eder – kimyasal kullanmadan.',                inhalt: '1 cihaz' },
  e13: { name: 'Yedek İnce Zımpara Ruloları (3\'lü)',   info: 'Nasır törpüsü sonrası son rötuş için ince kum.',                             inhalt: '3 adet' },
  e14: { name: 'Seyahat Boyu Mini Freze',               info: 'Tükenmez kalem kadar küçük – yolda tam performans.',                         inhalt: '1 cihaz + 2 başlık' },
  e15: { name: 'Elektrikli Ayak Isıtıcısı',             info: '3 kademeli, otomatik kapanmalı yumuşacık ısıtma botu.',                      inhalt: '1 cihaz' },
  e16: { name: 'Hava Basınçlı Masaj Cihazı',            info: 'Ayak ve baldırlar için nazik değişken basınç – 2 manşet.',                   inhalt: '1 cihaz' },

  /* --- Fußbäder & Zusätze --- */
  b1:  { name: 'Ölü Deniz Ayak Banyosu Tuzu',           info: 'Mineral açısından zengin tuz – rahatlatır ve besler.',                       inhalt: '500 g' },
  b2:  { name: 'Biberiyeli Ayak Banyosu Katkısı',       info: 'Yorgun ayaklar için canlandırıcı banyo katkısı.',                            inhalt: '250 ml' },
  b3:  { name: 'Lavantalı Kabarcık Tableti (8\'li)',    info: 'Her ayak banyosuna bir tablet – yatıştırıcı lavanta kokusu.',                inhalt: '8 tablet' },
  b4:  { name: 'Katlanabilir Ayak Küveti',              info: 'Yerden tasarruf sağlar, kaymaz tabanlı.',                                    inhalt: '1 adet' },
  b5:  { name: 'Ayaklar için Süt Banyosu',              info: 'Süt proteinli kremsi banyo katkısı.',                                        inhalt: '400 ml' },
  b6:  { name: 'Bazik Ayak Banyosu Tozu',               info: 'Uzun ve keyifli bir banyo için bazik pH değeri.',                            inhalt: '300 g' },
  b7:  { name: 'Ayak Banyosu Termometresi',             info: 'İdeal su sıcaklığını bir bakışta gösterir.',                                 inhalt: '1 adet' },
  b8:  { name: 'Banyo için Masaj Fırçası',              info: 'Yumuşak noktalı uçlar banyoda ayak tabanına masaj yapar.',                   inhalt: '1 adet' },
  b9:  { name: 'Okaliptüs Banyo Yağı',                  info: 'Ferahlatıcı yağ – her ayak banyosuna iki kapak yeterli.',                    inhalt: '200 ml' },
  b10: { name: 'Komple Ayak Banyosu Seti',              info: 'Küvet, tuz, fırça ve havlu bir arada.',                                      inhalt: '4 parçalı set' },
  b11: { name: 'Lavantalı Ayak Banyosu Tuzu',           info: 'Akşam banyosu için yatıştırıcı lavanta.',                                    inhalt: '500 g' },
  b12: { name: 'Naneli Kabarcık Tableti (8\'li)',       info: 'Ferahlatıcı nane – her ayak banyosuna bir tablet.',                          inhalt: '8 tablet' },
  b13: { name: 'Papatyalı Ayak Banyosu Katkısı',        info: 'Hassas ciltler için yumuşak bir klasik.',                                    inhalt: '250 ml' },
  b14: { name: 'Çay Ağacı Yağlı Banyo Katkısı',         info: 'Yıpranmış ayaklar için ferahlatıcı katkı.',                                  inhalt: '100 ml' },
  b15: { name: 'Masaj Noktalı Ayak Küveti',             info: 'Noktalı taban daha banyo sırasında ayak tabanına masaj yapar.',              inhalt: '1 adet' },
  b16: { name: 'Ayak Banyosu İkilisi: Tuz ve Yağ',      info: 'Ölü Deniz tuzu ve okaliptüs yağı avantajlı sette.',                          inhalt: '2 parçalı set' },

  /* --- Nagelpflege --- */
  n1:  { name: 'Damlalıklı Tırnak Yağı',                info: 'Jojoba ve E vitamini – tırnağı ve tırnak etini güçlendirir.',                inhalt: '10 ml' },
  n2:  { name: 'XL Tırnak Klipseri',                    info: 'Ekstra geniş yüzey – kalın ayak tırnakları için de uygun.',                  inhalt: '1 adet' },
  n3:  { name: 'Kılıflı Cam Törpü',                     info: 'Tırnak kenarını mühürler – ömür boyu keskin kalır.',                         inhalt: '1 adet' },
  n4:  { name: '2\'si 1 Arada Tırnak Bakım Kalemi',     info: 'Yağ kalemi ve itici bir arada – yolculuk için.',                             inhalt: '1 adet' },
  n5:  { name: 'Renksiz Bakım Ojesi',                   info: 'İpeksi parlaklık veren güçlendirici baz oje.',                               inhalt: '10 ml' },
  n6:  { name: '4 Yüzlü Tırnak Parlatma Bloğu',         info: 'Törpüle, düzleştir, parlat, mühürle – tek blokta.',                          inhalt: '1 adet' },
  n7:  { name: 'Tırnak Eti Sökücü Jel',                 info: 'Fazla tırnak etini 60 saniyede çözer.',                                      inhalt: '30 ml' },
  n8:  { name: 'Tırnak Onarım Serumu',                  info: 'Kırılgan tırnakları 4 haftada gözle görülür şekilde güçlendirir.',           inhalt: '15 ml' },
  n9:  { name: 'Karma Kum Törpü Seti (6\'lı)',          info: 'Kalından çok inceye altı törpü.',                                            inhalt: '6 adet' },
  n10: { name: 'Komple Tırnak Bakım Seti',              info: 'Yağ, klipser, cam törpü ve kalem hediye kutusunda.',                         inhalt: '4 parçalı set' },
  n11: { name: 'Gül Kokulu Tırnak Eti Yağı',            info: 'Tırnak etini besler – zarif gül kokusuyla.',                                 inhalt: '10 ml' },
  n12: { name: 'Tırnak Beyazlatma Kalemi',              info: 'Tırnağın serbest ucunu gözle görülür şekilde aydınlatır.',                   inhalt: '1 adet' },
  n13: { name: 'Düz Tırnak Makası',                     info: 'Düz kesim tırnak batmasını önlemeye yardımcı olur.',                         inhalt: '1 adet · 10 cm' },
  n14: { name: 'Zımpara Törpü (10\'lu)',                info: 'Günlük tırnak bakımı için yedek paket.',                                     inhalt: '10 adet' },
  n15: { name: 'Tırnak Sertleştirici Oje',              info: 'Yumuşak tırnakları 2 haftada belirgin şekilde sertleştirir.',                inhalt: '10 ml' },
  n16: { name: '7 Parçalı Manikür Çantası',             info: 'Tüm tırnak aletleri fermuarlı kılıf içinde.',                                inhalt: '7 parçalı set' },

  /* --- Hornhaut & Peeling --- */
  h1:  { name: 'Doğal Ponza Taşı',                      info: 'Gerçek volkanik ponza – duş için klasik.',                                   inhalt: '1 adet' },
  h2:  { name: 'Çift Taraflı Nasır Törpüsü',            info: 'Kaba ve ince yüzey – topuk ve taban için.',                                  inhalt: '1 adet' },
  h3:  { name: 'Deniz Tuzlu Ayak Peelingi',             info: 'Badem yağlı ince tuz peelingi – kadife gibi bir cilt.',                      inhalt: '150 ml' },
  h4:  { name: 'Nasır Azaltıcı Krem',                   info: 'Yeni nasır oluşumunu önleyen günlük bakım.',                                 inhalt: '75 ml' },
  h5:  { name: 'Peeling Çorabı (1 çift)',               info: 'Uygulayın, soyun, şaşırın – 7 günde yenilenme.',                             inhalt: '1 çift' },
  h6:  { name: 'Vanilyalı Şeker Peelingi',              info: 'Hassas ciltler için nazik peeling.',                                         inhalt: '200 ml' },
  h7:  { name: 'Seramik Nasır Taşı',                    info: 'Ponzadan daha ince – son rötuş için ideal.',                                 inhalt: '1 adet' },
  h8:  { name: 'Sisal Peeling Eldiveni',                info: 'Ayak ve bacaklar için doğal lifli eldiven.',                                 inhalt: '1 adet' },
  h9:  { name: 'Ayaklar için Üre Maskesi',              info: '%15 üre içeren yoğun maske – gece boyunca etki eder.',                       inhalt: '100 ml' },
  h10: { name: 'Pürüzsüz Ayaklar Seti',                 info: 'Törpü, peeling ve azaltıcı krem bir arada.',                                 inhalt: '3 parçalı set' },
  h11: { name: 'Yedek Raspa Bıçakları (10\'lu)',        info: 'Ayak bakım raspasıyla uyumlu – tek tek mühürlü.',                            inhalt: '10 adet' },
  h12: { name: 'Ponza Sırtlı Ayak Fırçası',             info: 'Fırça ve ponza taşı tek sapta.',                                             inhalt: '1 adet' },
  h13: { name: 'Canlandırıcı Kahve Peelingi',           info: 'Çekilmiş kahve ve hindistancevizi yağı – yorgun ayakları uyandırır.',        inhalt: '200 ml' },
  h14: { name: 'Nasır Balsamı Üre %10',                 info: 'Törpü veya raspa sonrası günlük bakım.',                                     inhalt: '100 ml' },
  h15: { name: 'Peeling Çorabı İkili Paket',            info: 'İki uygulama – 3 ayda bir kür için.',                                        inhalt: '2 çift' },
  h16: { name: '7 Günlük Pürüzsüz Topuk Kürü',          info: 'Bir haftalık maske, balsam ve kullanım kılavuzu.',                           inhalt: '2 parçalı set' },

  /* --- Komfort & Entlastung --- */
  k1:  { name: 'Jel Parmak Ayırıcı (2\'li)',            info: 'Yumuşak jel sıkışık parmakları rahatlatır.',                                 inhalt: '2 adet' },
  k2:  { name: 'Baskı Koruyucu Halkalar (6\'lı)',       info: 'Ayakkabıda sürtünmeye karşı kendinden yapışkanlı pedler.',                   inhalt: '6 adet' },
  k3:  { name: 'Jel Topuk Yastığı (çift)',              info: 'Her adımı yumuşatır – her ayakkabıya göre kesilebilir.',                     inhalt: '1 çift' },
  k4:  { name: 'Yumuşacık Wellness Çorabı',             info: 'ABS tabanlı peluş çorap – bakım sonrası tam bir keyif.',                     inhalt: '1 çift, 36–42 numara' },
  k5:  { name: 'Jel Parmak Koruma Kapakları (4\'lü)',   info: 'Hassas parmakları her ayakkabıda korur.',                                    inhalt: '4 adet' },
  k6:  { name: 'Kendinden Yapışkanlı Taban Pedi',       info: 'Uzun süre ayakta kalırken ön tabanı rahatlatır.',                            inhalt: '4 adet' },
  k7:  { name: 'Ahşap Masaj Rulosu',                    info: 'Gerginlikleri yuvarlayarak giderin – kayın ağacından.',                      inhalt: '1 adet' },
  k8:  { name: 'Kirpi Topu İkilisi',                    info: 'Aradaki aktif masajlar için iki noktalı top.',                               inhalt: '2 adet' },
  k9:  { name: 'Jel Konfor Tabanlığı',                  info: 'Darbe emici jel tabanlık, 36–46 numaraya göre kesilebilir.',                 inhalt: '1 çift' },
  k10: { name: 'Ayak Jimnastiği Seti',                  info: 'Güçlü ayaklar için top, bant ve egzersiz kılavuzu.',                         inhalt: '3 parçalı set' },
  k11: { name: 'Hafif Destek Çorabı (çift)',            info: 'Ayakta geçen uzun günler için hafif kompresyon.',                            inhalt: '1 çift, 36–46 numara' },
  k12: { name: 'Topuk Yastığı (çift)',                  info: 'Yumuşak ped her adımda topuğu rahatlatır.',                                  inhalt: '1 çift' },
  k13: { name: 'Parmak Yoga Ayırıcısı (çift)',          info: 'Uzun bir ayakkabı gününden sonra parmakları esnetir.',                       inhalt: '1 çift' },
  k14: { name: 'Ayaklar için Akupresür Matı',           info: 'Ayakta dururken ayak masajı için noktalı yüzey.',                            inhalt: '1 adet · 35 × 35 cm' },
  k15: { name: 'Büyük Boy Ayak Sıcak Su Torbası',       info: 'Ekstra geniş – iki ayağı aynı anda ısıtır.',                                 inhalt: '1 adet · 2 l' },
  k16: { name: 'Kaymaz Çorap (2 çift)',                 info: 'Kaygan zeminlerde güvenli tutuş – 60 °C\'de yıkanabilir.',                   inhalt: '2 çift, 36–46 numara' },

  /* --- Hygiene & Desinfektion --- */
  d1:  { name: 'El Dezenfektan Jeli',                   info: 'Aloe veralı, cilt dostu – yolculuk için.',                                   inhalt: '100 ml' },
  d2:  { name: 'Yüzey Dezenfektan Spreyi',              info: 'Hızlı etkili – cihazlar ve çalışma yüzeyleri için.',                         inhalt: '250 ml' },
  d3:  { name: 'Tek Kullanımlık Nitril Eldiven (100)',  info: 'Pudrasız, yırtılmaya dayanıklı – S–XL beden.',                               inhalt: '100 adet' },
  d4:  { name: 'Antibakteriyel Ayak Spreyi',            info: 'Ferahlatır ve korur – spor sonrası ideal.',                                  inhalt: '150 ml' },
  d5:  { name: 'Alet Dezenfeksiyon Küveti',             info: 'Alet bakımı için süzgeç ünitesi olan küvet.',                                inhalt: '1 adet · 1 l' },
  d6:  { name: 'Dezenfektan Konsantresi',               info: '25 litreye kadar kullanıma hazır çözelti elde edilir.',                      inhalt: '500 ml' },
  d7:  { name: 'Tek Kullanımlık Örtü (50\'li)',         info: 'Yüksek emici ve hijyenik – 40 × 60 cm.',                                     inhalt: '50 adet' },
  d9:  { name: 'Hijyen Seyahat Seti',                   info: 'Jel, sprey ve mendiller makyaj çantasında.',                                 inhalt: '3 parçalı set' },

  /* --- Geschenke & Gutscheine --- */
  g1:  { name: 'Profesyonel Ayak Bakımı Hediye Çeki',   info: 'Hediye etmenin klasiği – ev ziyaretinde eksiksiz bakım.',                    inhalt: '1 hediye çeki' },
  g2:  { name: 'Ayak Masajı Hediye Çeki',               info: 'Rahatlama hediye edin – evde keyifli bir masaj.',                            inhalt: '1 hediye çeki' },
  g3:  { name: 'Refleksoloji Masajı Hediye Çeki',       info: 'En kapsamlı uygulama hediye olarak.',                                        inhalt: '1 hediye çeki' },
  g4:  { name: '25 € Değerinde Hediye Çeki',            info: 'Hizmetlerde ve ürünlerde serbestçe kullanılabilir.',                         inhalt: '1 hediye çeki' },
  g5:  { name: '„Mutlu Ayaklar" Şımartma Seti',         info: 'Hediye kutusunda ayak banyosu tuzu, krem ve wellness çorabı.',               inhalt: '3 parçalı set' },
  g6:  { name: '„Ayaklara İlk Yardım" Hediye Kutusu',   info: 'Peeling, balsam ve tırnak yağı – şık paketlenmiş.',                          inhalt: '3 parçalı set' },
  g7:  { name: '„Fuß-Werk" Erkek Seti',                 info: 'Ona özel törpü, krem ve ferahlatıcı sprey.',                                 inhalt: '3 parçalı set' },
  g8:  { name: 'Zarflı Tebrik Kartı',                   info: 'Hediye çekiyle birlikte ideal – „Sana özel".',                               inhalt: '1 adet' },
  g9:  { name: 'Premium Hediye Paketi',                 info: 'Kutu, ipek kâğıt ve kurdele – hazır paketlenmiş.',                           inhalt: '1 adet' },
  g10: { name: '„4 × Bakım" Yıllık Paketi',             info: 'Önden dört ayak bakımı randevusu – bir randevu hediye.',                     inhalt: '4 hediye çeki' },
  g11: { name: '50 € Değerinde Hediye Çeki',            info: 'Hizmetlerde ve ürünlerde serbestçe kullanılabilir.',                         inhalt: '1 hediye çeki' },
  g12: { name: '100 € Değerinde Hediye Çeki',           info: 'Büyük hediye – serbestçe kullanılabilir.',                                   inhalt: '1 hediye çeki' },
  g13: { name: '„İki Kişilik" İkili Hediye Çeki',       info: 'İki ayak bakımı randevusu – örneğin çiftler için.',                          inhalt: '2 hediye çeki' },
  g14: { name: '„Kış Ayakları" Hediye Seti',            info: 'Isıtıcı balsam, peluş çorap ve banyo tuzu.',                                 inhalt: '3 parçalı set' },
  g15: { name: 'Küçük Bir Mutluluk',                    info: 'Tebrik kartıyla pratik boy ayak kremi – küçük bir jest.',                    inhalt: '2 parçalı set' },
  g16: { name: 'E-posta ile Hediye Çeki',               info: 'Anında gönderilir – son dakika hediyesi için ideal.',                        inhalt: '1 hediye çeki (PDF)' }
};
