// Norberts mobile Fußpflege — Shop-Übersetzung Chinesisch (vereinfacht).
// Wird in den zh/-Seiten VOR js/produkte.js geladen und stellt Texte,
// Kategorie-Titel und Produkt-Übersetzungen bereit (siehe Kopf von
// js/produkte.js). Der Bestelltext an Norbert bleibt IMMER deutsch.
window.NF_BASIS = '../';

window.NF_TEXTE = {
  artikel:         '件商品',
  titelZusatz:     ' – Norberts mobile Fußpflege 斯图加特',
  badgeNeu:        '新品',
  badgeBestseller: '畅销',
  aufLager:        '● 有货',
  wenig:           '● 库存有限',
  vonSternen:      '分(满分 5 星)',
  mengeMinus:      '减少数量',
  mengePlus:       '增加数量',
  inDenKorb:       '加入购物车',
  imKorb:          '✓ 已加入购物车',
  jetztKaufen:     '立即购买',
  entfernen:       '移除'
};

window.NF_KATEGORIEN = {
  w: '工具、器械与卫生用品',
  c: '护足霜与滋养膏',
  e: '电动仪器',
  b: '足浴与足浴用品',
  n: '指甲护理',
  h: '角质护理与去角质',
  k: '舒适与减压',
  g: '礼品与礼券'
};

window.NF_UEBERSETZUNG = {
  /* --- Werkzeuge & Instrumente --- */
  w1:  { name: '不锈钢角质钳',           info: '不锈钢材质,刃口精磨——温和去除角质。',                     inhalt: '1 件 · 14 cm' },
  w2:  { name: '专业指甲钳',             info: '省力杠杆设计,厚硬的指甲也能干净利落地剪断。',             inhalt: '1 件 · 12 cm' },
  w4:  { name: '三件套器械皮包',         info: '钳、锉、铲收纳于皮质套包中——外出携带的理想之选。',         inhalt: '3 件套装' },
  w5:  { name: '带刀片修脚铲',           info: '握持稳固,刀片可更换——仅限熟练者使用。',                   inhalt: '1 件 + 10 片刀片' },
  w6:  { name: '弯头趾甲剪',             info: '弯曲刀刃贴合指甲形状——温和而精准。',                       inhalt: '1 件 · 10 cm' },
  w7:  { name: '双头甲皮推',             info: '推起并分离甲皮——两个工作端。',                             inhalt: '1 件' },
  w9:  { name: '器械清洁刷',             info: '细密黄铜刷毛——保持锉刀和磨头清洁。',                       inhalt: '1 件' },
  w10: { name: '足部护理入门套装',       info: '6 件最重要的工具收纳于套包中——入门的理想之选。',           inhalt: '6 件套装' },

  /* --- Cremes & Balsame --- */
  c1:  { name: '尿素 10% 护足霜',        info: '为干燥、疲劳的双足深层补水。',                             inhalt: '100 ml' },
  c2:  { name: '金盏花足部滋养膏',       info: '舒缓滋养——含金盏花和蜂蜡。',                               inhalt: '75 ml' },
  c3:  { name: '强效防皲裂膏',           info: '为极度干燥的脚跟提供丰润滋养。',                           inhalt: '75 ml' },
  c4:  { name: '清新足部除臭喷雾',       info: '清新持久,经皮肤科测试。',                                 inhalt: '100 ml' },
  c5:  { name: '乳木果足部润肤霜',       info: '入肤即化的夜间滋养——含乳木果油和杏仁油。',                 inhalt: '150 ml' },
  c6:  { name: '薄荷清凉足部凝胶',       info: '为疲惫的腿脚带来清爽——快速吸收。',                         inhalt: '100 ml' },
  c7:  { name: '迷迭香按摩油',           info: '温热按摩油,在家享受足部按摩。',                           inhalt: '100 ml' },
  c8:  { name: '角质软化霜',             info: '一夜之间明显软化硬化部位。',                               inhalt: '75 ml' },
  c9:  { name: '速效护理泡沫',           info: '数秒即吸收——护理无需等待。',                               inhalt: '125 ml' },
  c10: { name: '冬季护理二件组',         info: '护足霜 + 防皲裂膏优惠套装。',                              inhalt: '套装 · 2 × 75 ml' },
  c11: { name: '尿素 25% 强效护足霜',    info: '针对极度干燥、皲裂皮肤的加强配方。',                       inhalt: '75 ml' },
  c12: { name: '月见草油滋养膏',         info: '夜间舒缓受刺激的敏感肌肤。',                               inhalt: '50 ml' },
  c13: { name: '锌元素护理霜',           info: '呵护受损肌肤——快速吸收。',                                 inhalt: '50 ml' },
  c14: { name: '生姜温热足部滋养膏',     info: '为冰凉的双足带来舒适暖意——冬季的理想之选。',               inhalt: '75 ml' },
  c15: { name: '无香型敏感肌护理霜',     info: '不含香料和色素——适合敏感肌肤。',                           inhalt: '100 ml' },
  c16: { name: '护理体验三件组',         info: '霜、膏、泡沫小样装,轻松试用。',                           inhalt: '套装 · 3 × 30 ml' },

  /* --- Elektrische Geräte --- */
  e1:  { name: '电动去角质磨脚器',       info: '两档速度,可充电——温和磨出光滑脚跟。',                     inhalt: '1 台 + 2 个滚轮' },
  e2:  { name: '10 件套电动打磨器',      info: '静音机身,配 10 个磨头,用于指甲和角质护理。',             inhalt: '1 套' },
  e3:  { name: '加热气泡足浴盆',         info: '气泡、震动加保温功能——在家享受水疗。',                     inhalt: '1 台' },
  e4:  { name: '替换磨砂滚轮(3 个装)', info: '适配电动磨脚器——中等粒度。',                               inhalt: '3 件' },
  e5:  { name: '护理甲油 UV 烘干器',     info: '60 秒烘干护理甲油。',                                      inhalt: '1 台' },
  e6:  { name: '笔式电动指甲锉',         info: '如笔般轻巧顺手——修形与增亮。',                             inhalt: '1 台 + 4 个磨头' },
  e7:  { name: '指压式足部按摩仪',       info: '旋转按摩头加温热功能——深度放松。',                         inhalt: '1 台' },
  e8:  { name: '替换打磨头(5 个装)',   info: '细腻金刚砂磨头,适配打磨器套装。',                         inhalt: '5 件' },
  e9:  { name: '足部石蜡浴机',           info: '温热石蜡令肌肤丝般柔滑——含 450 g 蜡。',                    inhalt: '1 台 + 石蜡' },
  e10: { name: '仪器旅行收纳盒',         info: '加垫硬壳盒,收纳磨脚器、打磨器及配件。',                   inhalt: '1 件' },
  e11: { name: '充电式指甲抛光器',       info: '抛光与封层——无线设计,配 3 个磨头。',                      inhalt: '1 台 + 3 个磨头' },
  e12: { name: 'UV 消毒盒',              info: '8 分钟为器械消毒——无需化学药剂。',                         inhalt: '1 台' },
  e13: { name: '替换磨砂滚轮细粒(3 个装)', info: '细粒度,用于去角质后的最后打磨。',                     inhalt: '3 件' },
  e14: { name: '迷你旅行打磨器',         info: '小如圆珠笔——外出也有十足动力。',                           inhalt: '1 台 + 2 个磨头' },
  e15: { name: '电热暖脚器',             info: '舒适的保暖鞋造型,3 档温度,自动断电。',                   inhalt: '1 台' },
  e16: { name: '空气压缩按摩仪',         info: '柔和交替气压,按摩双足和小腿——2 个腿套。',                 inhalt: '1 台' },

  /* --- Fußbäder & Zusätze --- */
  b1:  { name: '死海足浴盐',             info: '富含矿物质的浴盐——放松并滋养。',                           inhalt: '500 g' },
  b2:  { name: '迷迭香足浴液',           info: '提神醒足的足浴添加剂。',                                   inhalt: '250 ml' },
  b3:  { name: '薰衣草气泡浴片(8 片装)', info: '每次足浴一片——舒缓的薰衣草香。',                         inhalt: '8 片' },
  b4:  { name: '可折叠足浴盆',           info: '折叠收纳省空间,带防滑盆底。',                             inhalt: '1 件' },
  b5:  { name: '足部牛奶浴',             info: '含乳蛋白的柔滑足浴添加剂。',                               inhalt: '400 ml' },
  b6:  { name: '碱性足浴粉',             info: '碱性 pH 值,尽享舒适的长时间足浴。',                       inhalt: '300 g' },
  b7:  { name: '足浴温度计',             info: '一眼看清理想水温。',                                       inhalt: '1 件' },
  b8:  { name: '足浴按摩刷',             info: '柔软凸点,在足浴中按摩脚底。',                             inhalt: '1 件' },
  b9:  { name: '桉树足浴精油',           info: '清爽精油——每次足浴两瓶盖即可。',                           inhalt: '200 ml' },
  b10: { name: '足浴全套套装',           info: '浴盆、浴盐、浴刷和毛巾一套齐全。',                         inhalt: '4 件套装' },
  b11: { name: '薰衣草足浴盐',           info: '舒缓薰衣草,适合晚间足浴。',                               inhalt: '500 g' },
  b12: { name: '薄荷气泡浴片(8 片装)', info: '清新薄荷——每次足浴一片。',                                 inhalt: '8 片' },
  b13: { name: '洋甘菊足浴液',           info: '温和经典配方,适合敏感肌肤。',                             inhalt: '250 ml' },
  b14: { name: '茶树油足浴液',           info: '为疲劳双足带来清新的足浴添加剂。',                         inhalt: '100 ml' },
  b15: { name: '按摩凸点足浴盆',         info: '凸点盆底,泡脚的同时按摩脚底。',                           inhalt: '1 件' },
  b16: { name: '足浴二件组盐与油',       info: '死海浴盐加桉树精油优惠套装。',                             inhalt: '2 件套装' },

  /* --- Nagelpflege --- */
  n1:  { name: '滴管装指甲营养油',       info: '荷荷巴油与维生素 E——强韧指甲与甲皮。',                     inhalt: '10 ml' },
  n2:  { name: '加大号指甲剪',           info: '超大着力面——厚实的脚趾甲也能轻松应对。',                   inhalt: '1 件' },
  n3:  { name: '玻璃指甲锉带套',         info: '封闭平滑甲缘——终生锋利。',                                 inhalt: '1 件' },
  n4:  { name: '二合一指甲护理笔',       info: '营养油笔加甲皮推合二为一——外出适用。',                     inhalt: '1 件' },
  n5:  { name: '透明护理甲油',           info: '强韧底油,带来丝般光泽。',                                 inhalt: '10 ml' },
  n6:  { name: '四面抛光块',             info: '锉形、磨平、抛光、封层——一块搞定。',                       inhalt: '1 件' },
  n7:  { name: '甲皮软化凝胶',           info: '60 秒软化多余甲皮。',                                      inhalt: '30 ml' },
  n8:  { name: '指甲修护精华',           info: '4 周明显改善脆弱易断的指甲。',                             inhalt: '15 ml' },
  n9:  { name: '混合粒度指甲锉套装(6 件)', info: '六把锉刀,粒度从粗到超细。',                           inhalt: '6 件' },
  n10: { name: '指甲护理全套套装',       info: '营养油、指甲剪、玻璃锉和护理笔,礼盒装。',                 inhalt: '4 件套装' },
  n11: { name: '玫瑰香甲皮营养油',       info: '滋养甲皮——伴有淡雅玫瑰香。',                               inhalt: '10 ml' },
  n12: { name: '指甲增白笔',             info: '明显提亮指甲前缘。',                                       inhalt: '1 件' },
  n13: { name: '直头指甲剪',             info: '平直的剪法有助于避免甲角嵌入。',                           inhalt: '1 件 · 10 cm' },
  n14: { name: '砂纸指甲锉(10 件装)', info: '日常指甲护理的补充装。',                                   inhalt: '10 件' },
  n15: { name: '指甲强化甲油',           info: '2 周明显强韧偏软的指甲。',                                 inhalt: '10 ml' },
  n16: { name: '7 件套修甲包',           info: '全部指甲工具收纳于拉链包中。',                             inhalt: '7 件套装' },

  /* --- Hornhaut & Peeling --- */
  h1:  { name: '天然浮石',               info: '真正的火山浮石——淋浴时的经典之选。',                       inhalt: '1 件' },
  h2:  { name: '双面角质锉',             info: '粗细两面——适用于脚跟和前掌。',                             inhalt: '1 件' },
  h3:  { name: '海盐足部磨砂膏',         info: '细腻海盐磨砂配杏仁油——令肌肤丝滑。',                       inhalt: '150 ml' },
  h4:  { name: '角质修护霜',             info: '日常护理,预防新角质生成。',                               inhalt: '75 ml' },
  h5:  { name: '焕肤足膜袜(1 双)',     info: '敷上、揭下、见证惊喜——7 天焕新。',                         inhalt: '1 双' },
  h6:  { name: '香草砂糖磨砂膏',         info: '温和磨砂,适合敏感肌肤。',                                 inhalt: '200 ml' },
  h7:  { name: '陶瓷角质石',             info: '比浮石更细腻——最后打磨的理想之选。',                       inhalt: '1 件' },
  h8:  { name: '剑麻去角质手套',         info: '天然纤维手套,适用于足部和腿部。',                         inhalt: '1 件' },
  h9:  { name: '尿素足膜',               info: '含 15% 尿素的深层护理膜——夜间敷用。',                      inhalt: '100 ml' },
  h10: { name: '柔滑双足套装',           info: '角质锉、磨砂膏和修护霜一套齐全。',                         inhalt: '3 件套装' },
  h11: { name: '替换刀片(10 片装)',   info: '适配修脚铲——独立密封包装。',                               inhalt: '10 件' },
  h12: { name: '浮石背足刷',             info: '刷毛与浮石合于一柄。',                                     inhalt: '1 件' },
  h13: { name: '咖啡活力磨砂膏',         info: '咖啡粉与椰子油——唤醒疲惫双足。',                           inhalt: '200 ml' },
  h14: { name: '尿素 10% 角质滋养膏',    info: '锉磨之后的日常护理。',                                     inhalt: '100 ml' },
  h15: { name: '焕肤足膜袜双件装',       info: '两次用量——每 3 个月一次焕肤护理。',                        inhalt: '2 双' },
  h16: { name: '7 天脚跟柔滑护理组',     info: '足膜、滋养膏和使用指南,一周用量。',                       inhalt: '2 件套装' },

  /* --- Komfort & Entlastung --- */
  k1:  { name: '凝胶分趾器(2 个装)',   info: '柔软凝胶,舒缓相互挤压的脚趾。',                           inhalt: '2 件' },
  k2:  { name: '防压保护环(6 个装)',   info: '自粘软垫,防止鞋内摩擦。',                                 inhalt: '6 件' },
  k3:  { name: '凝胶后跟垫(一双)',     info: '缓冲每一步——可裁剪,适合各种鞋型。',                       inhalt: '1 双' },
  k4:  { name: '舒适保暖袜',             info: '柔软蓬松,带防滑底——护理之后的绝佳享受。',                 inhalt: '1 双 · 36–42 码' },
  k5:  { name: '凝胶护趾套(4 个装)',   info: '在任何鞋中保护敏感脚趾。',                                 inhalt: '4 件' },
  k6:  { name: '自粘前掌软垫',           info: '久站时减轻前脚掌负担。',                                   inhalt: '4 件' },
  k7:  { name: '木质按摩滚轮',           info: '轻松滚走紧绷疲劳——榉木制。',                               inhalt: '1 件' },
  k8:  { name: '刺球二件组',             info: '两个凸点球,随时进行活力按摩。',                           inhalt: '2 件' },
  k9:  { name: '凝胶舒适鞋垫',           info: '缓冲凝胶鞋垫,可裁剪,36–46 码。',                         inhalt: '1 双' },
  k10: { name: '足部体操套装',           info: '球、弹力带和练习指南,让双足更有力。',                     inhalt: '3 件套装' },
  k11: { name: '轻压力支撑袜(一双)',   info: '轻柔支撑,陪伴久站的漫长一天。',                           inhalt: '1 双 · 36–46 码' },
  k12: { name: '后跟软垫(一双)',       info: '柔软衬垫,每一步都减轻脚跟负担。',                         inhalt: '1 双' },
  k13: { name: '脚趾瑜伽分趾器(一双)', info: '穿鞋一整天后舒展放松脚趾。',                               inhalt: '1 双' },
  k14: { name: '足部指压垫',             info: '凸点垫面,站立即可按摩足底。',                             inhalt: '1 件 · 35 × 35 cm' },
  k15: { name: '加大号暖脚热水袋',       info: '超宽设计——双脚同时取暖。',                                 inhalt: '1 件 · 2 l' },
  k16: { name: '防滑袜(2 双装)',       info: '在光滑地面上稳固防滑——可 60 °C 机洗。',                    inhalt: '2 双 · 36–46 码' },

  /* --- Hygiene & Desinfektion --- */
  d1:  { name: '免洗手部消毒凝胶',       info: '含芦荟,温和护肤——外出适用。',                             inhalt: '100 ml' },
  d2:  { name: '表面消毒喷雾',           info: '快速起效——适用于仪器和工作台面。',                         inhalt: '250 ml' },
  d3:  { name: '丁腈一次性手套(100 只)', info: '无粉、抗撕裂——S 至 XL 码。',                             inhalt: '100 件' },
  d4:  { name: '抗菌足部喷雾',           info: '清爽防护——运动后的理想之选。',                             inhalt: '150 ml' },
  d5:  { name: '器械消毒浸泡盒',         info: '带滤篮的浸泡盒,用于器械养护。',                           inhalt: '1 件 · 1 l' },
  d6:  { name: '消毒浓缩液',             info: '可配制多达 25 l 即用溶液。',                               inhalt: '500 ml' },
  d7:  { name: '一次性垫巾(50 张装)', info: '吸水又卫生——40 × 60 cm。',                                 inhalt: '50 件' },
  d9:  { name: '卫生旅行套装',           info: '凝胶、喷雾和湿巾装于洗漱包中。',                           inhalt: '3 件套装' },

  /* --- Geschenke & Gutscheine --- */
  g1:  { name: '专业足部护理礼券',       info: '送礼经典之选——完整的上门足部护理。',                       inhalt: '1 张礼券' },
  g2:  { name: '足部按摩礼券',           info: '把放松作为礼物——舒适的居家按摩。',                         inhalt: '1 张礼券' },
  g3:  { name: '足部反射区按摩礼券',     info: '最充分尽兴的护理项目,作为礼物赠送。',                     inhalt: '1 张礼券' },
  g4:  { name: '25 € 面值礼券',          info: '可自由抵用各项服务和产品。',                               inhalt: '1 张礼券' },
  g5:  { name: '呵护套装“足部舒适”',     info: '足浴盐、护足霜和舒适袜,礼盒装。',                         inhalt: '3 件套装' },
  g6:  { name: '礼盒“足部救星”',         info: '磨砂膏、滋养膏和指甲营养油——精美包装。',                   inhalt: '3 件套装' },
  g7:  { name: '男士套装“足部工坊”',     info: '角质锉、护足霜和清新喷雾,为他准备。',                     inhalt: '3 件套装' },
  g8:  { name: '贺卡带信封',             info: '与礼券绝配——“送给你”。',                                   inhalt: '1 件' },
  g9:  { name: '高级礼品包装',           info: '礼盒、绵纸和缎带——包装妥当。',                             inhalt: '1 件' },
  g10: { name: '年度套餐“4 次护理”',     info: '预订四次专业足部护理——其中一次免费赠送。',                 inhalt: '4 张礼券' },
  g11: { name: '50 € 面值礼券',          info: '可自由抵用各项服务和产品。',                               inhalt: '1 张礼券' },
  g12: { name: '100 € 面值礼券',         info: '隆重的大礼——可自由抵用。',                                 inhalt: '1 张礼券' },
  g13: { name: '双人礼券“两人同行”',     info: '两次专业足部护理——例如送给伴侣。',                         inhalt: '2 张礼券' },
  g14: { name: '礼品套装“冬日暖足”',     info: '温热滋养膏、保暖袜和足浴盐。',                             inhalt: '3 件套装' },
  g15: { name: '小小心意',               info: '便携护足霜配贺卡——一份贴心的小礼。',                       inhalt: '2 件套装' },
  g16: { name: '电子邮件礼券',           info: '即刻发送——临时起意送礼的理想之选。',                       inhalt: '1 张礼券(PDF)' }
};
